############################
## CHANGE THESE
############################

baseURL: "https://yallup.github.io"
title: David Yallup

############################
## MISC
############################

enableEmoji: false
disableKinds: ["taxonomy", "term"]
languageCode: "en-us"
enableRobotsTXT: true

markup:
  _merge: deep
