############################
## Navigation
############################

main:
  - name: Home
    url: /
    weight: 10
  - name: About
    url: /about/
    weight: 20
  - name: Work
    url: /work/
    weight: 30
