############################
## Navigation
############################

main:
  - name: Home
    url: /
    weight: 10
  - name: About
    url: /about/
    weight: 20
  - name: Blog
    url: /blog/
    weight: 30
