############################
## Author
############################

author:
  name: David Yallup
  image: portrait.jpeg
  greeting: "Probabilistic inference, GPU acceleration, and generative AI for precision science"

############################
## Links
############################

links:
  - github: https://github.com/yallup
  - link: https://www.kicc.cam.ac.uk/staff/david-yallup
  - linkedin: https://www.linkedin.com/in/dyallup/
  - email: mailto:dy297@cam.ac.uk

############################
## OpenGraph & Twitter Cards
############################

title: David Yallup
description: Personal academic website of David Yallup, Research Associate at the University of Cambridge
images:
  - thumbnail.png
